import type {Metadata} from "next";

import {ThemeProvider} from "@/components/theme-provider";
import "./globals.css";
import {Navbar} from "@/components/navbar";

export const metadata: Metadata = {
  title: "movies-app",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system">
        <body className="bg-background">
          <Navbar />
          <main className="px-3">{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
