import type {Metadata} from "next";

import "./globals.css";
import Link from "next/link";
import {Clapperboard, Home, Tv, UserRound} from "lucide-react";

import {Navbar} from "@/components/navbar/navbar";
import {NavbarSearchMovie} from "@/components/navbar/navbar-search-movie";

export const metadata: Metadata = {
  title: "movies-app",
  description: "Generated by appncy",
};
const links = [
  {name: "Home", path: "/", icon: <Home />},
  {name: "Movies", path: "/movies", icon: <Clapperboard />},
  {name: "Tv Series", path: "/tv", icon: <Tv />},
  {name: "People", path: "/people", icon: <UserRound />},
];

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="w-full overflow-x-hidden bg-background">
        <Navbar />
        <main
          className={`*:transition-[margin_width] *:duration-500
        [&>*:nth-child(1)]:ml-[-100%]
         peer-checked:[&>*:nth-child(1)]:ml-[0%]
        
        peer-checked:[&>*:nth-child(2)]:ml-[200px]
        md:peer-checked:[&>*:nth-child(2)]:w-[calc(100vw-200px)]
        `}
        >
          <nav className="fixed left-0 top-16 z-30 flex h-[calc(100dvh-64px)] w-[200px] flex-col gap-6 bg-background px-2 py-2">
            <NavbarSearchMovie />
            <ul className="flex flex-grow flex-col gap-2">
              {links.map(({name, path, icon}, index) => {
                return (
                  <li key={index}>
                    <Link
                      className="flex items-center justify-start gap-2 rounded-md border-2 border-border bg-background p-2 duration-300 hover:border-gradient hover:pl-3 hover:text-gradient [&>*:nth-child(1)]:size-4" //icon size
                      href={path}
                    >
                      {icon}
                      {name}
                    </Link>
                  </li>
                );
              })}
            </ul>
          </nav>
          <section className="fixed top-16 h-[calc(100dvh-64px)] w-full overflow-auto px-2">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
